### ISSUE TITLE
Correct Serialization of google::protobuf::Struct

### ISSUE THREAD

**Issue by jackpertschuk** [influxdata/pbjson#10]
Is there a list somewhere of supported proto well known types. I don't see coverage for structs and I wondered if they're supported

**Comment by tustvold** [comment]
I'm afraid support for Values (#5) and by extension Struct is not currently supported. I would welcome PRs to add this functionality, and would be happy to provide guidance if this is something you would be interested in adding?

**Comment by tustvold** [comment]
Closed by #16
