### ISSUE TITLE
Correct Serialization of google::protobuf::*Value Types

### ISSUE THREAD

**Issue by tustvold** [influxdata/pbjson#3]
From https://developers.google.com/protocol-buffers/docs/proto3#json

> Wrappers use the same representation in JSON as the wrapped primitive type, except that null is allowed and preserved during data conversion and transfer.

Currently the wrapper types are not special cased and are therefore not serialized/deserialized to/from this custom representation. This should be fixed

**Comment by tustvold** [comment]
> which seems to conflict with the JSON mapping docs.

Where is the conflict? The JSON mapping I think consistently renders 64-bit integral types as strings? This is because javascript stores all numbers as 64-bit floating point - which only have 52-bit integral precision

**Comment by rise0chen** [comment]
How's it going? I'm looking forward to this feature.

**Comment by tustvold** [comment]
I don't really have time to work on this at the moment, but if you or anyone else were willing to submit PRs, I would happily review them

**Comment by rise0chen** [comment]
#63 I have submit a PR.
But BytesValue can't work
