### ISSUE TITLE
Support Explicit JSON `null`

### ISSUE THREAD

**Issue by rise0chen** [influxdata/pbjson#73]
Failed to deserialize when `google::protobuf::*Value` is `null`

**Comment by rise0chen** [comment]
I can't impl Deserialize for Option<google::protobuf::*Value>

**Comment by tustvold** [comment]
I'm not sure I understand the problem? Could you perhaps provide an example of some JSON that behaves incorrectly?

**Comment by rise0chen** [comment]
```
message KitchenSink {
  google.protobuf.UInt64Value uint64_value = 56;
}
```

```
{"uint64Value": null}
```

**Comment by tustvold** [comment]
Does this work?

```
message Other {}

message KitchenSink {
    Other other = 1;
}
```

```
{"other": null}
```

I'm not seeing why `UInt64Value` would be any different from a normal message, and wonder if there is a more general issue here?

**Comment by rise0chen** [comment]
not work

**Comment by tustvold** [comment]
Ok I'll have a play, I have some ideas of what is going on
