### ISSUE TITLE
Option to Emit Default Values When Serializing

### ISSUE THREAD

**Issue by EiffelFly** [influxdata/pbjson#82]
I very much appreciate that you build and maintain this package, it's very insightful and helpful. 

Recently I am facing a serious problem when implementing axum-tonic on the same server. I want to utilize the protobuf generated type as the single source of truth across the whole services including rest API. But by default prost will omit the default value so does pbjson (If I understand it correctly). I wonder does there have any chance that we can force the generate Serializer to not omit a specific field's default value.

The re-producible repo is here:

https://github.com/EiffelFly/axum-tonic-api

**Comment by tustvold** [comment]
As per the specification

> An implementation may provide options to emit fields with default values in the JSON-encoded output.

It would therefore be perfectly acceptable to add a [builder option](https://docs.rs/pbjson-build/latest/pbjson_build/struct.Builder.html) to emit default values, much like retain_enum_prefix or ignore_unknown_fields.

Would you be interested in implementing such a feature, or shall I add it to my list?

**Comment by EiffelFly** [comment]
@tustvold Thanks for the follow up!!

I am very willing to contribute, but could you lighten up the path that I can start with?

**Comment by tustvold** [comment]
In fact this feature has already been implemented :facepalm: 

https://github.com/influxdata/pbjson/pull/66

You can enable it with https://docs.rs/pbjson-build/latest/pbjson_build/struct.Builder.html#method.emit_fields on the Builder

**Comment by EiffelFly** [comment]
@tustvold Thanks for your clarification haha, I miss this field too! I think in this case we can close this issue.
