### ISSUE TITLE
Question: How to use pbjson types like ListValue or Value to form the data

### ISSUE THREAD

**Issue by EiffelFly** [influxdata/pbjson#84]
I am using pbjson with protoc-gen-prost together to generate the protobuf types. And I really want to use these types as single source of truth to form the data of response. Like this line did https://github.com/EiffelFly/axum-tonic-api/blob/52fd23a085572c9964bfdb5c370d62e1f20db1d3/src/rest_handler/mod.rs#L12

```rust 
pub async fn greeter_handler(
    Json(data): Json<pb::helloworld::HelloRequest>,
) -> Result<impl IntoResponse, Response> {
    let resp = pb::helloworld::HelloResponse { <----- Use protobuf generated type
        message: format!("Hello {}", data.name),
        test_array: Vec::new(),
    };

    Ok((StatusCode::OK, Json(resp)))
}
```
Everything is ok until I am facing the google well-known-types like Value and ListValue.

Take this one for example.

If I have protobuf like this

```proto
message Tag {
  string name = 1;
  google.protobuf.ListValue resources = 2;
}
```

And here is my db type

```rust
#[derive(Queryable, Serialize, Deserialize, Debug)]
pub struct Tag {
    pub name: String,
    pub resources: Vec<ResourceUnion>,
}

pub enum ResourceUnion {
    DiscordGuild(DiscordGuild),
    DiscordThread(DiscordThread),
    DiscordMessage(DiscordMessage),
    Website(Website),
}
```

How can I convert the Vec<ResourceUnion> to ListValue. It looks like I have to implement the From for ResourceUnion?

```rust
impl From<ResourceUnion> for Value {
    fn from(values: ResourceUnion) -> Self {
        match values {
            ResourceUnion::DiscordGuild(DiscordGuild) => {
                let fields: HashMap<String, Value> = HashMap::new();
                fields.insert(
                    "guild_id".to_string(),
                    pbjson_types::Value::from(DiscordGuild.guild_id),  //<---- How to convert i64 to Value
                );

                fields.insert(
                    "name".to_string(),
                    pbjson_types::Value::from(DiscordGuild.name),
                );

                fields.insert(
                    "tags".to_string(),
                    pbjson_types::Value::from(DiscordGuild.tags), //<---- Seems like I need to implement From for Vec<Tag> too
                );

                return Value {
                    kind: Some(Kind::StructValue(Struct { fields })),
                };
            }
        }
    }
}
```

**Comment by tustvold** [comment]
I'm confused the generated output for

```
message Tag {
  string name = 1;
  google.protobuf.ListValue resources = 2;
}
```

Is

```
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tag {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub resources: ::core::option::Option<::pbjson_types::ListValue>,
}
```

**Comment by EiffelFly** [comment]
> I'm confused the generated output for

> message Tag {
>   string name = 1;
>   google.protobuf.ListValue resources = 2;
> }
> Is
> 
> #[derive(Clone, PartialEq, ::prost::Message)]
> pub struct Tag {
>     #[prost(string, tag="1")]
>     pub name: ::prost::alloc::string::String,
>     #[prost(message, optional, tag="2")]
>     pub resources: ::core::option::Option<::pbjson_types::ListValue>,
> }

Do you mean this generated types doesn't make sense to you? But I think I can't control the generation of this part of code or I am wrong.

**Comment by tustvold** [comment]
Sorry I'm not sure I follow what you are asking, `ListValue` is a type-erased container, using it for strongly typed contents is a little peculiar. Have you considered doing something like


```
message DiscordGuild {
    ...
}

message DiscordThread {
    ...
}

message ResourceUnion {
    oneof resource {
        DiscordGuild guild = 1;
        DiscordThread thread = 2;
        ...
    } 
}

message Tag {
  string name = 1;
  repeated ResourceUnion resources = 2;
}
```

**Comment by EiffelFly** [comment]
WOW!! You are right!!

Although I will face some circular issue, I think this is the right way to go!

**Comment by tustvold** [comment]
I don't think this is tracking anything anymore, so closing. Feel free to reopen if I am mistaken
