### ISSUE TITLE
Error: out of range integral type conversion attempted

### ISSUE THREAD

**Issue by NAlexandrov** [influxdata/pbjson#85]
When I try deserialize next value, I've got an error "out of range integral type conversion attempted".
```rs
    let json = r#"{"num": 5000000000}"#;
    let obj: serde_json::Value = serde_json::from_str(json)?;
    println!("num {}", obj["num"]);

    let vec = serde_json::to_vec(&obj).unwrap();
    let pb = serde_json::from_slice::<pbjson_types::Value>(&vec).unwrap();
    println!("{:#?}", pb);
```
This happens because next [function](https://github.com/influxdata/pbjson/blob/main/pbjson-types/src/value.rs#L186-L191) throw an error:
```rs
    fn visit_u64<E>(self, v: u64) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        self.visit_u32(v.try_into().map_err(de::Error::custom)?)
    }
```
If look [visit_u32](https://github.com/influxdata/pbjson/blob/7197cb4d44643be0bcf94cb925ceb57223c78edf/pbjson-types/src/value.rs#L179-L184) function, so number value wrapped in Kind::NumberValue which accept f64 type:
```rs
    fn visit_u32<E>(self, v: u32) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        Ok(Kind::NumberValue(v.into())) // f64
    }
```
As a result, the current conversion pipeline looks like u64 -> u32 -> f64. If it were u64 -> f64 (without u32), then we would not lose a significant range of numerical values (u32, f64].

For example like this:
```rs
    fn visit_u64<E>(self, v: u64) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        Ok(Kind::NumberValue(
            v.to_string().parse::<f64>().map_err(de::Error::custom)?,
        ))
    }
```

**Comment by tustvold** [comment]
Hi @NAlexandrov, thank you for the report.

I would be happy to review a PR that makes this change, otherwise I can add it to my list but I am not sure when I will have time to get to it.

_FWIW the protobuf JSON representation recommends serializing 64-bt integers as strings, as `f64` only has 52-bit precision, but I presume you are aware of this._
