### ISSUE TITLE
Issue when using types from different paths?

### ISSUE THREAD

**Issue by brocaar** [influxdata/pbjson#9]
First of all, thanks for providing this package :+1: 

I'm trying to use this package together with `tonic_build` (which is using `prost_build`), and this works well when all types are within the same path (so far I've only tested the code generation path). However, I'm running into issues when some types within different paths.

Example directory layout:

```
api.proto
common/common.proto
```

When `api.proto` uses a type (in my case `Region`) from `common/proto.proto`, the generated pbjson code should have the appropriate prefix. For `tonic_build`, I manually configure this using, and this works well:

```rust
.extern_path(".common", "crate::common")
```

However, for `pbjson_build` no such method exist (I believe) and the code generator is assuming all imported types exist within the same scope, resulting in for example the following error:

```
3769 |             let v = Region::from_i32(self.region)                                                                                                    
     |                     ^^^^^^ not found in this scope                                                                                                   
     |                                                                                                                                                      
help: consider importing this enum                                                                                                                          
     |                                                                                                                                                      
6    | use crate::common::Region;
```

Is this indeed a feature that is missing, or is there something that I'm missing?

**Comment by brocaar** [comment]
@tustvold could you provide any feedback on the above? Am I something missing or is this indeed a config option that is not yet available?

**Comment by tustvold** [comment]
@brocaar Apologies, I completely missed this - I will look into today

**Comment by tustvold** [comment]
So a couple of points here:

Prost, and by extension tonic and pbjson, assume that the module topology within Rust matches the package topology in the protobuf. It uses this to insert the requisite number of `super::*` to the callsites. An example of this can be found in IOx where the `include!` macro invocations are nested in modules - https://github.com/influxdata/influxdb_iox/blob/6320ce6f557ee96983ca58e111599b091fc7677e/generated_types/src/lib.rs#L9

Pbjson does not currently support extern_path, but I think it should be relatively straightforward to support. I will look into adding support for this

**Comment by tustvold** [comment]
Continuing to investigate this, found another bug in this space which I think is likely what you're hitting. The code generation for enum fields defined in other packages is incorrect. I will fix this also :+1:

**Comment by brocaar** [comment]
Thanks @tustvold for looking into this :+1:

**Comment by tustvold** [comment]
@brocaar I've published v0.2.1 could you confirm if this fixes your issue

**Comment by brocaar** [comment]
@tustvold Thanks! I'll validate today.

**Comment by brocaar** [comment]
I can no longer reproduce the issue :+1:
